version: 2.1
orbs:
    aws-s3: circleci/aws-s3@2.0.0
jobs:
    build:
        docker:
            - image: circleci/python:2.7-node
        steps:
            - checkout
            - run: npm install
            - run: npm run build
            - aws-s3/sync:
                  arguments: |
                      --acl public-read \
                      --cache-control "max-age=86400" \
                  aws-access-key-id: AWS_S3_ACCESS_KEY_ID
                  aws-region: AWS_S3_REGION
                  aws-secret-access-key: AWS_S3_SECRET_ACCESS_KEY
                  from: dist
                  to: "s3://demo-ci-cd-article-270120/"
workflows:
    version: 2.1
    build:
        jobs:
            - build:
                  filters:
                      branches:
                          only: master
